import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <Container className="w-full h-full items-center justify-center flex" >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CardContainer className="flex flex-col items-center justify-center" >
        <div className="w-full flex justify-start text-black font-bold text-2xl">
            Join the community of sellers or sign in 
        </div>
        <div className="flex w-full items-center justify-around">
          <Link href="/signin"><Btn>Sign In</Btn></Link>
          <Link href="/signup"><Btn>Sign Up</Btn></Link>
          
        </div>
      </CardContainer>
    </Container>
  )
}

const Container = styled.div`
    width: 100%;
    min-height: 100vh;
    background-color: #dfe3e7;
    padding: 100px 20px;
`
const CardContainer = styled.div`
    width: 500px;
    height: 400px;
    bax-shadow: 0 5px 10px rgb(0 0 0 / 15%), 0 0 0 rgb(0 0 0 / 8%) inset;
    background-color: white;
    border-radius: 8px;
    padding: 16px;
`
const PInput = styled.div`
    margin-top: 10px;
    >label{
        font-size: 14px;
        font-weight: 600;
        text-align: left;
        width: 100%;

    }
    >input{
        height: 40px;
        border: 1px solid #abb5c0;
        border-radius: 5px;
        font-size: 14px;
        padding-left: 5px;
        :focus{
            outline: none;
            border: 3px solid #068eef;
        }
    }
`
const Btn = styled.div`
    display: flex;
    justify-content: center;
    align-items: center;
    margin-top: 20px;
    padding: 10px 4px;
    background-color: #068eef;
    color: white;
    font-size: 20px;
    cursor: pointer;
    font-weight: 900;
    border-radius: 6px;
    width: 200px;
`