import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="w-full h-full flex" >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Foot>
        <h1 className="text-sm">Fg</h1>
      </Foot>
    </div>
  )
}

const Foot = styled.div`
  width: 200px;
  height: 200px;
  background-color: yellow;
`